### ISSUE TITLE
Recorder crashes when playing a second file

### ISSUE THREAD

**Issue by egkoppel** [EZ-Code-Developer/sound-recorder#6]
When the user plays a file, then stops it (either with the stop button or when it ends) and then tries to play another one. I think this is because the app calls `mediaPlayer.stop();` when it is already stopped.

**Comment by egkoppel** [comment]
Pushed in commit 5ef81d0cca6fd91849fb670d3ba697aefa27d051

**Comment by egkoppel** [comment]
But the stop button doesn't go when the file stops playing

**Comment by ZeevoX** [comment]
Because it doesn't need to

**Comment by egkoppel** [comment]
But how can you stop something that is already stopped

**Comment by egkoppel** [comment]
And why doesn't it need to?

**Comment by ZeevoX** [comment]
It needs to have a status of disabled
